### ISSUE TITLE
[DOCS] Typo error in README file

### ISSUE THREAD

**Issue by VishwaS-22** [Pradumnasaraf/Kubernetes#2] opened 2022-10-21 04:36 UTC
### Description

Hey @Pradumnasaraf ! 
There is a typo error in the readme file of Kubernetes as well as same error in the Description part also. Can you please fix that or Can I work on this and make a PR? because these contributions also help me .
Happy to contribute to the OpenSource.  

### Screenshots

![Screenshot (107)](https://user-images.githubusercontent.com/85573504/197112871-f87b18f2-3c0b-4787-b51a-491ffde810e9.png)
![Screenshot (108)](https://user-images.githubusercontent.com/85573504/197112885-8c747ced-6a14-455d-8970-b7e4bb7c4b69.png)

**Comment by Pradumnasaraf** [comment] 2022-10-21 18:20
Hey, thanks for opening the issue, the issue is already fixed in a branch but hasn't been merged.

**Closed by Pradumnasaraf** 2022-10-21 18:20 UTC
Labels: documentation

**Comment by VishwaS-22** [comment] 2022-10-23 06:27
My pleasure Pradumna, Oh ok! Happy to Contribute.
Thank You.
